stages:
  - validate-staging
  - deploy-staging
  - destroy-staging
  - validate-production
  - deploy-production
  - destroy-production

cache:
  key: ${CI_COMMIT_REF_SLUG}-terraform
  paths:
    - environments/staging/.terraform/
    - environments/production/.terraform/

.terraform_base:
  image:
    name: hashicorp/terraform:1.7
    entrypoint: [""]

validate_staging:
  extends: .terraform_base
  stage: validate-staging
  script:
    - cd environments/staging
    - terraform init
    - terraform fmt -check
    - terraform validate
  only:
    - main

deploy_staging:
  extends: .terraform_base
  stage: deploy-staging
  script:
    - cd environments/staging
    - terraform init
    - terraform apply -auto-approve
  only:
    - main

destroy_staging:
  extends: .terraform_base
  stage: destroy-staging
  script:
    - cd environments/staging
    - terraform init
    - terraform destroy -auto-approve
  only:
    - main
  when: manual

validate_production:
  extends: .terraform_base
  stage: validate-production
  script:
    - cd environments/production
    - terraform init
    - terraform fmt -check
    - terraform validate
  only:
    - main

deploy_production:
  extends: .terraform_base
  stage: deploy-production
  script:
    - cd environments/production
    - terraform init
    - terraform apply -auto-approve
  only:
    - main
  when: manual

destroy_production:
  extends: .terraform_base
  stage: destroy-production
  script:
    - cd environments/production
    - terraform init
    - terraform destroy -auto-approve
  only:
    - main
  when: manual
